"""Generate inputs/references.bib from the corpus sidecar, and report gaps.

Only a missing author or venue blocks anything — a bib entry does not need a DOI
or an abstract, and reporting those as problems just buries the real ones.

Corrections belong upstream in the corpus sidecar, never in the generated .bib.

Usage:
    python build_bib.py                 # write the bib, report gaps
    python build_bib.py --check         # report only, write nothing
    python build_bib.py --keys          # print the bibkey <-> title map
"""

import argparse
import re
from pathlib import Path

from common import (Progress, add_project_arg, disambiguate, find_project,
                    load_corpus, make_bibkey, now_iso, print_json)

BLOCKING = ("authors", "venue")

# crude but adequate: proceedings-ish venues become @inproceedings
JOURNALISH = re.compile(
    r"journal|transactions|tmlr|jmlr|nature|science|arxiv|corr|preprint|"
    r"letters|review|patterns|quarterly|magazine", re.I)


def escape(value: str) -> str:
    return (value or "").replace("{", "").replace("}", "").replace("\\", "").strip()


def entry_type(record: dict) -> str:
    venue = record.get("venue") or ""
    if not venue:
        return "misc"
    return "article" if JOURNALISH.search(venue) else "inproceedings"


def render(key: str, record: dict) -> str:
    kind = entry_type(record)
    fields = [("title", "{%s}" % escape(record.get("title")))]
    authors = record.get("authors") or []
    if authors:
        fields.append(("author", " and ".join(escape(a) for a in authors)))
    venue = escape(record.get("venue"))
    if venue:
        fields.append(("booktitle" if kind == "inproceedings" else "journal", venue))
    if record.get("year"):
        fields.append(("year", str(record["year"])))
    if record.get("doi"):
        fields.append(("doi", escape(record["doi"])))
    body = ",\n  ".join("%s = {%s}" % (k, v.strip("{}") if k == "title" else v)
                        for k, v in fields)
    return "@%s{%s,\n  %s\n}\n" % (kind, key, body)


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    add_project_arg(parser)
    parser.add_argument("--check", action="store_true", help="report gaps, write nothing")
    parser.add_argument("--keys", action="store_true", help="print the key map and exit")
    args = parser.parse_args()

    project = find_project(args.project)
    records = load_corpus(project)

    keys = disambiguate([make_bibkey(r) for r in records])
    for i, record in enumerate(records):
        record["_key"] = keys[i]

    if args.keys:
        print_json({"keys": [{"bibkey": r["_key"], "title": r.get("title"),
                              "file": r.get("path") or r.get("key")} for r in records]})
        return

    blocking, soft = [], []
    for record in records:
        missing = [f for f in BLOCKING if not record.get(f)]
        if missing:
            blocking.append({"bibkey": record["_key"], "title": (record.get("title") or "")[:70],
                             "missing": missing, "file": record.get("key")})
        if not record.get("doi"):
            soft.append(record["_key"])

    out = project / "inputs" / "references.bib"
    written = 0
    if not args.check:
        out.parent.mkdir(parents=True, exist_ok=True)
        with out.open("w") as handle:
            handle.write("%% generated by surveylevelup build_bib.py — do not edit\n")
            handle.write("%% corrections belong in the corpus sidecar, then re-run\n\n")
            for record in sorted(records, key=lambda r: r["_key"]):
                handle.write(render(record["_key"], record) + "\n")
                written += 1

        progress = Progress(project)
        progress.data.setdefault("counts", {})["bib"] = written
        progress.data.setdefault("bib", {})["built"] = now_iso()
        progress.data["bib"]["blocking_gaps"] = len(blocking)
        progress.log("build_bib", entries=written, blocking_gaps=len(blocking))
        progress.save()

    print_json({
        "corpus_records": len(records),
        "entries_written": written,
        "path": str(out) if written else None,
        "blocking_gaps": blocking,
        "blocking_gap_count": len(blocking),
        "missing_doi_count": len(soft),
        "note": "a missing DOI or abstract does not block; fix authors and venue "
                "in the corpus sidecar via paperlevelup, then re-run",
    })


if __name__ == "__main__":
    main()
